### ISSUE TITLE
Starting the webserver via Readme didn't work

### ISSUE THREAD

**Issue by XenoLupus** [KK4TEE/kFacts#1]
# Error in Readme.md
```
2. Change to the project directory:

cd kFacts
cd kFacts
```

This should be 
```
cd kFacts
cd api_server
```

# npm start Error
npm install worked. Installed 36 packages, however then running npm start produced following Output:
```
[...]\kFacts\api_server>npm start
npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     [...]\AppData\Local\npm-cache\_logs\2023-04-18T17_25_11_132Z-debug-0.log
```

The logfile doesn't produce more information.

Running npm run produced following output:
```
[...]\kFacts\api_server>npm run
Lifecycle scripts included in api_server@1.0.0:
  test
    mocha
```

**Comment by KK4TEE** [comment]
Thank you for opening the issue! I've made the corrections and pushed them to main. `npm start` should now work. Please let me know if you find anything else.

**Comment by KK4TEE** [comment]
I'm still working on getting the pathing set up. Right now the mod uses hardcoded paths and assumes it is in the mods/kFacts/api_server directory. [app.js](https://github.com/KK4TEE/kFacts/blob/main/api_server/app.js) can be modified to suit other locations. I am planning to add better pathing soon.
